import type { NextPage } from 'next'
import Head from 'next/head'

import { 
  S01,
  S02L,
  S03,
  S04,
  S05,
  S06,
  S07,
  S08,
  S09,
  S10, 
  S11,
} from '../sections'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hitachi Sustainability</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <S01 />
        <S02L />
        <S03 />
        <S04 />
        <S05 />
        <S06 />
        <S07 />
        <S08 />
        <S09 />
        <S10 />
        <S11 />
      </main>
    </div>
  )
}

export default Home
