import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import S02 from './sections/02'
import S03 from './sections/03'
import S04 from './sections/04'
import S05 from './sections/05'
import S06 from './sections/06'
import S07 from './sections/07'
import S08 from './sections/08'
import S09 from './sections/09'
import S10 from './sections/10'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <S02 />
        <S03 />
        <S04 />
        <S05 />
        <S06 />
        <S07 />
        <S08 />
        <S09 />
        <S10 />
        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
